import React, { useState } from 'react';
import  ReactDOM from 'react-dom';
import MyModal from './Showmodal';
import moment from 'moment';

const MyPortal=()=>{
    return ReactDOM.createPortal(<>
    <h1>Portal Design here</h1>
    </>,document.getElementById('new-root'))
}



const Modal = () => {
    const [showModal,setShowModal]=useState(false);
 
    const handleModal=()=>setShowModal(true);
    
    const handleClose=()=>setShowModal(false);
    
   
    return (
        <div>
            <MyPortal/>
           <button onClick={handleModal}>Open Modal</button>      
          {showModal && <MyModal handleit={handleClose}/>} 
         
        
          <h4>{moment().endOf('day').fromNow()}</h4>
          {/* <h4>{moment().format()}</h4> */}
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla dui in convallis condimentum. Maecenas nec nisi a magna imperdiet aliquet non in ligula. Curabitur a nisl fermentum, lobortis libero non, molestie elit. Nunc blandit vestibulum odio eu tristique. Vestibulum nec volutpat justo, id condimentum purus. Nulla dictum sapien sit amet mi pellentesque, a vestibulum dolor euismod. Sed vel libero efficitur, lacinia diam ut, imperdiet est. Aliquam nulla turpis, suscipit eu est volutpat, ornare elementum arcu. Integer in elit at nunc sollicitudin pretium. Morbi sodales rhoncus libero, at malesuada libero mollis non. Vivamus in ornare nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris malesuada, turpis eget lobortis dapibus, odio erat mollis libero, ut euismod urna augue sed ante. Suspendisse non elementum purus.</p>

        </div>
    );
};

export default Modal;      